- apt_repository:
    repo: 'ppa:ondrej/nginx'
    update_cache: 'yes'
  become: yes
  
- name: install nginx
  apt:
    name: nginx
    state: latest
  become: true

- name: Configure nginx
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - restart nginx

- name: Configure default server block
  template:
    src: default-nginx.conf
    dest: /etc/nginx/conf.d/default.conf
    owner: root
    group: root
    mode: 0644
  become: yes
  notify:
    - restart nginx

- name: ensure nginx service is running and enabled at boot
  service:
    name: nginx
    state: started
    enabled: yes
  become: yes
